modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="legendary_weapons"
version="1.0.0"
displayName="Legendary weapons"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="junph, MCreator"

[[dependencies.legendary_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




